update validator
tobycm/dummy-json-api pull request #1
Opened 2023-01-31 13:36 UTC by code-ga

2023-02-04 00:42 UTC, tobycm requested changes
Wow thanks ông đã đóng góp cho cái project bé nhỏ này :>
Ông xem mấy cái review nha :>

2023-02-04 00:42 UTC, tobycm commented on lib/request/validator.dart
> -  if (request.method != 'GET') {
Ông add lại cái check mà method ko phải GET hay POST thì return 405 Method Not Allowed đc ko ông?

2023-02-04 00:42 UTC, tobycm commented on lib/request/validator.dart
> +    }
thêm dòng trống ở đây đi ông :3

2023-02-04 00:42 UTC, tobycm commented on lib/request/validator.dart
> +    for (var element in rawData) {
đổi element thành data đi ông

2023-02-04 00:42 UTC, tobycm commented on lib/request/validator.dart
> -  if (request.method != 'GET') {
để mấy cái check này ở trên top cho nó dễ đọc code á ông, h tôi lướt xuống dưới ms thấy else return 405 :>

2023-02-04 00:42 UTC, tobycm commented on RequestDoc.md
> +```GET /random?data=<name>[;number],...```
number là gì thế ông, ghi giải thích nhaa :>

2023-02-04 00:42 UTC, tobycm commented on lib/request/validator.dart
> +        var looping = int.tryParse(option[1]);
cũng như cái looping này đổi tên luôn nha ông :>

2023-02-04 00:42 UTC, tobycm commented on routes/random_data.dart
> +  for (var e in requestData) {
e là gì thế ông x_x

2023-02-04 00:42 UTC, tobycm commented on lib/request/validator.dart
> +  } else if (request.method == "POST") {
Tôi nghĩ là chia code cho GET vs POST vào 2 function nhỉ

2023-02-05 01:11 UTC, code-ga commented on lib/request/validator.dart
> +  } else if (request.method == "POST") {
tạm thời để nó trong cùng 1 hàm đi bro

2023-02-05 01:20 UTC, code-ga commented on lib/request/validator.dart
> +    for (var element in rawData) {
oke

2023-02-05 01:25 UTC, code-ga commented on RequestDoc.md
> +```GET /random?data=<name>[;number],...```
số doc muốn gen ra

2023-02-05 20:21 UTC, tobycm approved these changes
thx ông nhiều nhaa
luv u :3

2023-02-05 20:21 UTC, merged